import { Spell } from './MagicTypes.js';
import { SpellBuilder } from './SpellBuilder.js';
import { CurseArmorBreakEffect, MagicDamageEffect, RageEffect, SlowEffect } from './SpellEffects.js';

export function createSpellBook(): Spell[] {
    return [
        new SpellBuilder()
            .withId('fireball-lvl-1')
            .withName('Fire Ball I')
            .withDescription('A burning projectile that deals armor-piercing magic damage.')
            .withTargetType('enemy')
            .withLevel(1)
            .withManaCost(3)
            .withEffect(new MagicDamageEffect(4, 2))
            .build(),
        new SpellBuilder()
            .withId('fireball-lvl-2')
            .withName('Fire Ball II')
            .withDescription('A stronger fireball with amplified impact.')
            .withTargetType('enemy')
            .withLevel(2)
            .withManaCost(5)
            .withEffect(new MagicDamageEffect(4, 2))
            .build(),
        new SpellBuilder()
            .withId('curse-lvl-1')
            .withName('Curse I')
            .withDescription('Weakens enemy protection and chips away with magic.')
            .withTargetType('enemy')
            .withLevel(1)
            .withManaCost(3)
            .withEffect(new CurseArmorBreakEffect(1, 1, 2))
            .withEffect(new MagicDamageEffect(2, 1))
            .build(),
        new SpellBuilder()
            .withId('curse-lvl-2')
            .withName('Curse II')
            .withDescription('Longer curse and stronger magical corrosion.')
            .withTargetType('enemy')
            .withLevel(2)
            .withManaCost(5)
            .withEffect(new CurseArmorBreakEffect(1, 1, 2))
            .withEffect(new MagicDamageEffect(2, 1))
            .build(),
        new SpellBuilder()
            .withId('slow-lvl-1')
            .withName('Slow I')
            .withDescription('Makes an enemy lose turns.')
            .withTargetType('enemy')
            .withLevel(1)
            .withManaCost(2)
            .withEffect(new SlowEffect(1))
            .build(),
        new SpellBuilder()
            .withId('slow-lvl-2')
            .withName('Slow II')
            .withDescription('Longer temporal drag for enemy turns.')
            .withTargetType('enemy')
            .withLevel(2)
            .withManaCost(4)
            .withEffect(new SlowEffect(1))
            .build(),
        new SpellBuilder()
            .withId('rage-lvl-1')
            .withName('Rage I')
            .withDescription('Empowers your attacks and spells for a short duration.')
            .withTargetType('self')
            .withLevel(1)
            .withManaCost(2)
            .withEffect(new RageEffect(2, 1.25, 0.15))
            .build(),
        new SpellBuilder()
            .withId('rage-lvl-2')
            .withName('Rage II')
            .withDescription('Greater and longer self-buff.')
            .withTargetType('self')
            .withLevel(2)
            .withManaCost(4)
            .withEffect(new RageEffect(2, 1.25, 0.15))
            .build(),
        new SpellBuilder()
            .withId('arcane-lance-lvl-1')
            .withName('Arcane Lance I')
            .withDescription('Focused arcane strike that pierces armor.')
            .withTargetType('enemy')
            .withLevel(1)
            .withManaCost(2)
            .withEffect(new MagicDamageEffect(3, 2))
            .build(),
        new SpellBuilder()
            .withId('arcane-lance-lvl-2')
            .withName('Arcane Lance II')
            .withDescription('Sharper lance with increased magical pressure.')
            .withTargetType('enemy')
            .withLevel(2)
            .withManaCost(4)
            .withEffect(new MagicDamageEffect(3, 2))
            .build(),
    ];
}
