// Generated by Duud
// Exports only slider/keyframe data for the selected animation

import type { ImportedAnimationMeta, ImportedKeyframe } from './types.js';

export const FLY_KEYFRAMES: ImportedKeyframe[] = [
    {
        time: 0,
        params: {
            x: 400,
            y: 301,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: -0.72,
            leftElbowAngle: 0.52,
            rightShoulderAngle: 0.83,
            rightElbowAngle: -0.48,
            leftHipAngle: -0.73,
            leftKneeAngle: 1.3,
            rightHipAngle: 1,
            rightKneeAngle: -1.57
        }
    },
    {
        time: 1,
        params: {
            x: 400,
            y: 301,
            headTilt: 0.08,
            torsoAngle: -0.05,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: -0.72,
            leftElbowAngle: 0.52,
            rightShoulderAngle: 0.72,
            rightElbowAngle: -0.52,
            leftHipAngle: -0.64,
            leftKneeAngle: 1.25,
            rightHipAngle: 0.92,
            rightKneeAngle: -1.41
        }
    }
];

export const FLY_META: ImportedAnimationMeta = {
    name: "Fly",
    duration: 1,
    loop: true
};
