// Generated by Duud
// Exports only slider/keyframe data for the selected animation

import type { ImportedAnimationMeta, ImportedKeyframe } from './types.js';

export const IDLE_KEYFRAMES: ImportedKeyframe[] = [
    {
        time: 0,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: 0.22,
            leftElbowAngle: 2.74,
            rightShoulderAngle: 1.05,
            rightElbowAngle: 2.1,
            leftHipAngle: -0.03,
            leftKneeAngle: -0.04,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.03
        }
    },
    {
        time: 1,
        params: {
            x: 401,
            y: 299,
            headTilt: 0,
            torsoAngle: -0.02,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: 0.62,
            leftElbowAngle: 1.98,
            rightShoulderAngle: 0.97,
            rightElbowAngle: 2.1,
            leftHipAngle: -0.03,
            leftKneeAngle: -0.04,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.03
        }
    },
    {
        time: 2,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: 0.22,
            leftElbowAngle: 2.74,
            rightShoulderAngle: 1.05,
            rightElbowAngle: 2.1,
            leftHipAngle: -0.03,
            leftKneeAngle: -0.04,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.03
        }
    }
];

export const IDLE_META: ImportedAnimationMeta = {
    name: "Idle",
    duration: 2,
    loop: true
};
