// Generated by Duud
// Exports only slider/keyframe data for the selected animation

import type { ImportedAnimationMeta, ImportedKeyframe } from './types.js';

export const KICK_KEYFRAMES: ImportedKeyframe[] = [
    {
        time: 0,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 23,
            shoulderLength: 37,
            leftShoulderAngle: -0.08,
            leftElbowAngle: 0.06,
            rightShoulderAngle: 0.16,
            rightElbowAngle: -0.03,
            leftHipAngle: -0.02,
            leftKneeAngle: 0,
            rightHipAngle: 0.02,
            rightKneeAngle: 0
        }
    },
    {
        time: 0.45,
        params: {
            x: 400,
            y: 300,
            headTilt: 0.05,
            torsoAngle: -0.08,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 23,
            shoulderLength: 37,
            leftShoulderAngle: -0.3,
            leftElbowAngle: 0.12,
            rightShoulderAngle: 0.45,
            rightElbowAngle: -0.3,
            leftHipAngle: -0.2,
            leftKneeAngle: -0.15,
            rightHipAngle: -1.05,
            rightKneeAngle: -0.95
        }
    },
    {
        time: 1,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 23,
            shoulderLength: 37,
            leftShoulderAngle: -0.08,
            leftElbowAngle: 0.06,
            rightShoulderAngle: 0.16,
            rightElbowAngle: -0.03,
            leftHipAngle: -0.02,
            leftKneeAngle: 0,
            rightHipAngle: 0.02,
            rightKneeAngle: 0
        }
    }
];

export const KICK_META: ImportedAnimationMeta = {
    name: 'Kick',
    duration: 1,
    loop: false
};

