import type { ImportedAnimationMeta, ImportedPoseKeyframe } from './types.js';

export const PUNCH_KEYFRAMES: ImportedPoseKeyframe[] = [
    {
        "time": 0,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -8,
            "leftElbowY": 0,
            "leftHandX": -8,
            "leftHandY": 8,
            "rightShoulderX": 5,
            "rightShoulderY": -12,
            "rightElbowX": 8,
            "rightElbowY": -8,
            "rightHandX": 8,
            "rightHandY": -8,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -3,
            "leftKneeY": 15,
            "leftFootX": -3,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 3,
            "rightKneeY": 15,
            "rightFootX": 3,
            "rightFootY": 25
        }
    },
    {
        "time": 0.25,
        "pose": {
            "headY": -20,
            "torsoEndY": 7.5,
            "leftShoulderX": -5,
            "leftShoulderY": -9.5,
            "leftElbowX": -10,
            "leftElbowY": 0,
            "leftHandX": -10,
            "leftHandY": 8,
            "rightShoulderX": 5,
            "rightShoulderY": -14.5,
            "rightElbowX": 16,
            "rightElbowY": -10.5,
            "rightHandX": 20,
            "rightHandY": -10.5,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -5,
            "leftKneeY": 15,
            "leftFootX": -5,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 5,
            "rightKneeY": 15,
            "rightFootX": 5,
            "rightFootY": 25
        }
    },
    {
        "time": 0.5,
        "pose": {
            "headY": -20,
            "torsoEndY": 10,
            "leftShoulderX": -5,
            "leftShoulderY": -7,
            "leftElbowX": -12,
            "leftElbowY": 0,
            "leftHandX": -12,
            "leftHandY": 8,
            "rightShoulderX": 5,
            "rightShoulderY": -17,
            "rightElbowX": 24,
            "rightElbowY": -13,
            "rightHandX": 32,
            "rightHandY": -13,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -7,
            "leftKneeY": 15,
            "leftFootX": -7,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 7,
            "rightKneeY": 15,
            "rightFootX": 7,
            "rightFootY": 25
        }
    },
    {
        "time": 0.75,
        "pose": {
            "headY": -20,
            "torsoEndY": 7.5,
            "leftShoulderX": -5,
            "leftShoulderY": -9.5,
            "leftElbowX": -10,
            "leftElbowY": 0,
            "leftHandX": -10,
            "leftHandY": 8,
            "rightShoulderX": 5,
            "rightShoulderY": -14.5,
            "rightElbowX": 16,
            "rightElbowY": -10.5,
            "rightHandX": 20,
            "rightHandY": -10.5,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -5,
            "leftKneeY": 15,
            "leftFootX": -5,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 5,
            "rightKneeY": 15,
            "rightFootX": 5,
            "rightFootY": 25
        }
    },
    {
        "time": 1,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -8,
            "leftElbowY": 0,
            "leftHandX": -8,
            "leftHandY": 8,
            "rightShoulderX": 5,
            "rightShoulderY": -12,
            "rightElbowX": 8,
            "rightElbowY": -8,
            "rightHandX": 8,
            "rightHandY": -8,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -3,
            "leftKneeY": 15,
            "leftFootX": -3,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 3,
            "rightKneeY": 15,
            "rightFootX": 3,
            "rightFootY": 25
        }
    }
];

export const PUNCH_META: ImportedAnimationMeta = {
    "name": "Punch",
    "duration": 1,
    "loop": false
};
