import type { ImportedAnimationMeta, ImportedPoseKeyframe } from './types.js';

export const STRONG_PUNCH_KEYFRAMES: ImportedPoseKeyframe[] = [
    {
        "time": 0,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -10,
            "leftElbowY": 2,
            "leftHandX": -12,
            "leftHandY": 10,
            "rightShoulderX": 6,
            "rightShoulderY": -12,
            "rightElbowX": 10,
            "rightElbowY": -10,
            "rightHandX": 12,
            "rightHandY": -10,
            "leftHipX": -4,
            "leftHipY": 6,
            "leftKneeX": -6,
            "leftKneeY": 16,
            "leftFootX": -6,
            "leftFootY": 26,
            "rightHipX": 4,
            "rightHipY": 6,
            "rightKneeX": 6,
            "rightKneeY": 12,
            "rightFootX": 6,
            "rightFootY": 20
        }
    },
    {
        "time": 0.3,
        "pose": {
            "headY": -18.8,
            "torsoEndY": 8,
            "leftShoulderX": -5,
            "leftShoulderY": -8,
            "leftElbowX": -13,
            "leftElbowY": 2,
            "leftHandX": -15,
            "leftHandY": 10,
            "rightShoulderX": 6,
            "rightShoulderY": -16,
            "rightElbowX": 18.4,
            "rightElbowY": -14,
            "rightHandX": 26,
            "rightHandY": -14,
            "leftHipX": -4.6,
            "leftHipY": 9,
            "leftKneeX": -9,
            "leftKneeY": 19,
            "leftFootX": -9,
            "leftFootY": 29,
            "rightHipX": 5,
            "rightHipY": 9,
            "rightKneeX": 9,
            "rightKneeY": 15,
            "rightFootX": 11,
            "rightFootY": 23
        }
    },
    {
        "time": 0.6,
        "pose": {
            "headY": -17.6,
            "torsoEndY": 11,
            "leftShoulderX": -5,
            "leftShoulderY": -4,
            "leftElbowX": -16,
            "leftElbowY": 2,
            "leftHandX": -18,
            "leftHandY": 10,
            "rightShoulderX": 6,
            "rightShoulderY": -20,
            "rightElbowX": 26.8,
            "rightElbowY": -18,
            "rightHandX": 40,
            "rightHandY": -18,
            "leftHipX": -5.2,
            "leftHipY": 12,
            "leftKneeX": -12,
            "leftKneeY": 22,
            "leftFootX": -12,
            "leftFootY": 32,
            "rightHipX": 6,
            "rightHipY": 12,
            "rightKneeX": 12,
            "rightKneeY": 18,
            "rightFootX": 16,
            "rightFootY": 26
        }
    },
    {
        "time": 0.8,
        "pose": {
            "headY": -18.8,
            "torsoEndY": 7.999999999999999,
            "leftShoulderX": -5,
            "leftShoulderY": -8,
            "leftElbowX": -13,
            "leftElbowY": 2,
            "leftHandX": -15,
            "leftHandY": 10,
            "rightShoulderX": 6,
            "rightShoulderY": -16,
            "rightElbowX": 18.4,
            "rightElbowY": -14,
            "rightHandX": 25.999999999999996,
            "rightHandY": -14,
            "leftHipX": -4.6,
            "leftHipY": 9,
            "leftKneeX": -9,
            "leftKneeY": 19,
            "leftFootX": -9,
            "leftFootY": 29,
            "rightHipX": 5,
            "rightHipY": 9,
            "rightKneeX": 9,
            "rightKneeY": 15,
            "rightFootX": 11,
            "rightFootY": 23
        }
    },
    {
        "time": 1,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -10,
            "leftElbowY": 2,
            "leftHandX": -12,
            "leftHandY": 10,
            "rightShoulderX": 6,
            "rightShoulderY": -12,
            "rightElbowX": 10,
            "rightElbowY": -10,
            "rightHandX": 12,
            "rightHandY": -10,
            "leftHipX": -4,
            "leftHipY": 6,
            "leftKneeX": -6,
            "leftKneeY": 16,
            "leftFootX": -6,
            "leftFootY": 26,
            "rightHipX": 4,
            "rightHipY": 6,
            "rightKneeX": 6,
            "rightKneeY": 12,
            "rightFootX": 6,
            "rightFootY": 20
        }
    }
];

export const STRONG_PUNCH_META: ImportedAnimationMeta = {
    "name": "Strong Punch",
    "duration": 1,
    "loop": false
};
