import type { ImportedAnimationMeta, ImportedPoseKeyframe } from './types.js';

export const TAUNT_KEYFRAMES: ImportedPoseKeyframe[] = [
    {
        "time": 0,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -10,
            "leftElbowY": 2,
            "leftHandX": -8,
            "leftHandY": 10,
            "rightShoulderX": 5,
            "rightShoulderY": -12,
            "rightElbowX": 15,
            "rightElbowY": -15,
            "rightHandX": 12,
            "rightHandY": -20,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -6,
            "leftKneeY": 15,
            "leftFootX": -8,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 6,
            "rightKneeY": 15,
            "rightFootX": 8,
            "rightFootY": 25
        }
    },
    {
        "time": 0.25,
        "pose": {
            "headY": -21.5,
            "torsoEndY": 6.5,
            "leftShoulderX": -5,
            "leftShoulderY": -10.5,
            "leftElbowX": -10,
            "leftElbowY": 2,
            "leftHandX": -8,
            "leftHandY": 10,
            "rightShoulderX": 5,
            "rightShoulderY": -14.25,
            "rightElbowX": 20,
            "rightElbowY": -22.5,
            "rightHandX": 12,
            "rightHandY": -27.5,
            "leftHipX": -4,
            "leftHipY": 5,
            "leftKneeX": -7,
            "leftKneeY": 15,
            "leftFootX": -9,
            "leftFootY": 25,
            "rightHipX": 4,
            "rightHipY": 5,
            "rightKneeX": 7,
            "rightKneeY": 15,
            "rightFootX": 9,
            "rightFootY": 25
        }
    },
    {
        "time": 0.5,
        "pose": {
            "headY": -23,
            "torsoEndY": 8,
            "leftShoulderX": -5,
            "leftShoulderY": -9,
            "leftElbowX": -10,
            "leftElbowY": 2,
            "leftHandX": -8,
            "leftHandY": 10,
            "rightShoulderX": 5,
            "rightShoulderY": -16.5,
            "rightElbowX": 25,
            "rightElbowY": -30,
            "rightHandX": 16,
            "rightHandY": -33,
            "leftHipX": -5,
            "leftHipY": 5,
            "leftKneeX": -8,
            "leftKneeY": 15,
            "leftFootX": -10,
            "leftFootY": 25,
            "rightHipX": 5,
            "rightHipY": 5,
            "rightKneeX": 8,
            "rightKneeY": 15,
            "rightFootX": 10,
            "rightFootY": 25
        }
    },
    {
        "time": 0.75,
        "pose": {
            "headY": -21.5,
            "torsoEndY": 6.5,
            "leftShoulderX": -5,
            "leftShoulderY": -10.5,
            "leftElbowX": -10,
            "leftElbowY": 2,
            "leftHandX": -8,
            "leftHandY": 10,
            "rightShoulderX": 5,
            "rightShoulderY": -14.25,
            "rightElbowX": 20,
            "rightElbowY": -22.5,
            "rightHandX": 16,
            "rightHandY": -25.5,
            "leftHipX": -4,
            "leftHipY": 5,
            "leftKneeX": -7,
            "leftKneeY": 15,
            "leftFootX": -9,
            "leftFootY": 25,
            "rightHipX": 4,
            "rightHipY": 5,
            "rightKneeX": 7,
            "rightKneeY": 15,
            "rightFootX": 9,
            "rightFootY": 25
        }
    },
    {
        "time": 1,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -10,
            "leftElbowY": 2,
            "leftHandX": -8,
            "leftHandY": 10,
            "rightShoulderX": 5,
            "rightShoulderY": -12,
            "rightElbowX": 15,
            "rightElbowY": -15,
            "rightHandX": 12,
            "rightHandY": -20,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -6,
            "leftKneeY": 15,
            "leftFootX": -8,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 6,
            "rightKneeY": 15,
            "rightFootX": 8,
            "rightFootY": 25
        }
    }
];

export const TAUNT_META: ImportedAnimationMeta = {
    "name": "Taunt",
    "duration": 1,
    "loop": true
};
