import type { ImportedAnimationMeta, ImportedPoseKeyframe } from './types.js';

export const WALK_KEYFRAMES: ImportedPoseKeyframe[] = [
    {
        "time": 0,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -8,
            "leftElbowY": 0,
            "leftHandX": -8,
            "leftHandY": 8,
            "rightShoulderX": 5,
            "rightShoulderY": -12,
            "rightElbowX": 8,
            "rightElbowY": 0,
            "rightHandX": 8,
            "rightHandY": 8,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -3,
            "leftKneeY": 15,
            "leftFootX": -3,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 3,
            "rightKneeY": 15,
            "rightFootX": 3,
            "rightFootY": 25
        }
    },
    {
        "time": 0.25,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -8,
            "leftElbowY": -5,
            "leftHandX": -8,
            "leftHandY": 0.5,
            "rightShoulderX": 5,
            "rightShoulderY": -12,
            "rightElbowX": 8,
            "rightElbowY": 5,
            "rightHandX": 8,
            "rightHandY": 15.5,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": 1,
            "leftKneeY": 15,
            "leftFootX": 5,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": -1,
            "rightKneeY": 15,
            "rightFootX": -5,
            "rightFootY": 25
        }
    },
    {
        "time": 0.5,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -8,
            "leftElbowY": -6.123233995736766e-16,
            "leftHandX": -8,
            "leftHandY": 7.999999999999999,
            "rightShoulderX": 5,
            "rightShoulderY": -12,
            "rightElbowX": 8,
            "rightElbowY": 6.123233995736766e-16,
            "rightHandX": 8,
            "rightHandY": 8.000000000000002,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -2.9999999999999996,
            "leftKneeY": 15,
            "leftFootX": -2.999999999999999,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 2.9999999999999996,
            "rightKneeY": 15,
            "rightFootX": 2.999999999999999,
            "rightFootY": 25
        }
    },
    {
        "time": 0.75,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -8,
            "leftElbowY": 5,
            "leftHandX": -8,
            "leftHandY": 15.5,
            "rightShoulderX": 5,
            "rightShoulderY": -12,
            "rightElbowX": 8,
            "rightElbowY": -5,
            "rightHandX": 8,
            "rightHandY": 0.5,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -7,
            "leftKneeY": 15,
            "leftFootX": -11,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 7,
            "rightKneeY": 15,
            "rightFootX": 11,
            "rightFootY": 25
        }
    },
    {
        "time": 1,
        "pose": {
            "headY": -20,
            "torsoEndY": 5,
            "leftShoulderX": -5,
            "leftShoulderY": -12,
            "leftElbowX": -8,
            "leftElbowY": 1.2246467991473533e-15,
            "leftHandX": -8,
            "leftHandY": 8.000000000000002,
            "rightShoulderX": 5,
            "rightShoulderY": -12,
            "rightElbowX": 8,
            "rightElbowY": -1.2246467991473533e-15,
            "rightHandX": 8,
            "rightHandY": 7.999999999999998,
            "leftHipX": -3,
            "leftHipY": 5,
            "leftKneeX": -3.000000000000001,
            "leftKneeY": 15,
            "leftFootX": -3.0000000000000018,
            "leftFootY": 25,
            "rightHipX": 3,
            "rightHipY": 5,
            "rightKneeX": 3.000000000000001,
            "rightKneeY": 15,
            "rightFootX": 3.0000000000000018,
            "rightFootY": 25
        }
    }
];

export const WALK_META: ImportedAnimationMeta = {
    "name": "Walk",
    "duration": 1,
    "loop": true
};
