import { SelectedCellInfo } from '../../types/game.js';

type PlayerStat = 'vitality' | 'toughness' | 'strength' | 'agility' | 'connection' | 'intelligence';

export type PendingSkillAllocations = Record<PlayerStat, number>;

export type HudElements = {
    usePotionBtn: HTMLButtonElement;
    useManaPotionBtn: HTMLButtonElement;
    playerLevel: HTMLElement;
    playerName: HTMLElement;
    playerXp: HTMLElement;
    playerXpNext: HTMLElement;
    playerHp: HTMLElement;
    playerMaxHp: HTMLElement;
    playerMana: HTMLElement;
    playerMaxMana: HTMLElement;
    playerDmg: HTMLElement;
    playerDmgFormula: HTMLElement;
    playerArmor: HTMLElement;
    playerDodge: HTMLElement;
    playerDodgeFormula: HTMLElement;
    playerWeapon: HTMLElement;
    playerGold: HTMLElement;
    playerClock: HTMLElement;
    playerDate: HTMLElement;
    worldCalendarSummary: HTMLElement;
    worldCalendarList: HTMLElement;
    playerFatigue: HTMLElement;
    playerFatigueState: HTMLElement;
    skillPoints: HTMLElement;
    magicPoints: HTMLElement;
    magicPanelPoints: HTMLElement;
    statVitality: HTMLElement;
    statToughness: HTMLElement;
    statStrength: HTMLElement;
    statAgility: HTMLElement;
    statConnection: HTMLElement;
    statIntelligence: HTMLElement;
    addVitalityBtn: HTMLButtonElement;
    subVitalityBtn: HTMLButtonElement;
    addToughnessBtn: HTMLButtonElement;
    subToughnessBtn: HTMLButtonElement;
    addStrengthBtn: HTMLButtonElement;
    subStrengthBtn: HTMLButtonElement;
    addAgilityBtn: HTMLButtonElement;
    subAgilityBtn: HTMLButtonElement;
    addConnectionBtn: HTMLButtonElement;
    subConnectionBtn: HTMLButtonElement;
    addIntelligenceBtn: HTMLButtonElement;
    subIntelligenceBtn: HTMLButtonElement;
    saveSkillsBtn: HTMLButtonElement;
    godSkillsBtn: HTMLButtonElement;
    upgradeFireballBtn: HTMLButtonElement;
    upgradeCurseBtn: HTMLButtonElement;
    upgradeSlowBtn: HTMLButtonElement;
    upgradeRageBtn: HTMLButtonElement;
    upgradeArcaneLanceBtn: HTMLButtonElement;
    spellLevelFireball: HTMLElement;
    spellLevelCurse: HTMLElement;
    spellLevelSlow: HTMLElement;
    spellLevelRage: HTMLElement;
    spellLevelArcaneLance: HTMLElement;
    spellDetailsFireball: HTMLElement;
    spellDetailsCurse: HTMLElement;
    spellDetailsSlow: HTMLElement;
    spellDetailsRage: HTMLElement;
    spellDetailsArcaneLance: HTMLElement;
    inventoryCount: HTMLElement;
    inventoryCapacity: HTMLElement;
    inventoryCapacityHint: HTMLElement;
    undoLastDropBtn: HTMLButtonElement;
    inventoryGrid: HTMLElement;
    weaponSlotMain: HTMLButtonElement;
    weaponSlotOff: HTMLButtonElement;
    armorSlot: HTMLButtonElement;
    statsPanel: HTMLElement;
    skillsPanel: HTMLElement;
    inventoryPanel: HTMLElement;
    magicPanel: HTMLElement;
    questsPanel: HTMLElement;
    selectedPanel: HTMLElement;
    lorePanel: HTMLElement;
    groupPanel: HTMLElement;
    worldMapPanel: HTMLElement;
    logPanel: HTMLElement;
    rosterPanel: HTMLElement;
    questsBody: HTMLElement;
    groupBody: HTMLElement;
    loreBody: HTMLElement;
    selectedCellEmpty: HTMLElement;
    selectedCellDetails: HTMLElement;
    selectedCellCoords: HTMLElement;
    selectedCellTerrain: HTMLElement;
    selectedCellVisibility: HTMLElement;
    selectedCellTraversable: HTMLElement;
    selectedCellVillage: HTMLElement;
    selectedCellVillageName: HTMLElement;
    selectedCellVillageStatus: HTMLElement;
    toggleStatsPanelBtn: HTMLButtonElement;
    toggleSkillsPanelBtn: HTMLButtonElement;
    toggleInventoryPanelBtn: HTMLButtonElement;
    toggleMagicPanelBtn: HTMLButtonElement;
    toggleQuestsPanelBtn: HTMLButtonElement;
    toggleGroupPanelBtn: HTMLButtonElement;
    toggleLorePanelBtn: HTMLButtonElement;
    toggleSelectedPanelBtn: HTMLButtonElement;
    toggleWorldMapPanelBtn: HTMLButtonElement;
    toggleLogPanelBtn: HTMLButtonElement;
    toggleRosterPanelBtn: HTMLButtonElement;
};

export type HudPanel = 'stats' | 'skills' | 'inventory' | 'magic' | 'quests' | 'group' | 'lore' | 'selected' | 'worldMap' | 'log' | 'roster';

export type BattleUiHudElements = {
    usePotionBtn: HTMLButtonElement;
    useManaPotionBtn: HTMLButtonElement;
    attackRangeText: HTMLElement;
    spellFireballBtn: HTMLButtonElement;
    spellCurseBtn: HTMLButtonElement;
    spellSlowBtn: HTMLButtonElement;
    spellRageBtn: HTMLButtonElement;
    spellArcaneLanceBtn: HTMLButtonElement;
};

export type BattleEquipmentActionHandler = (actionDescription: string) => boolean;
export type SelectedCellPresenter = (selectedCell: SelectedCellInfo | null) => void;
