export const itemBalance = {
    monsterDropChance: 0.35,
    discoveryPool: [
        { id: 'healingPotion', weight: 4 },
        { id: 'knife_t1', weight: 10 },
        { id: 'knife_t2', weight: 10 },
        { id: 'knife_t3', weight: 10 },
        { id: 'knife_t4', weight: 10 },
        { id: 'shortSword_t1', weight: 9 },
        { id: 'shortSword_t2', weight: 9 },
        { id: 'shortSword_t3', weight: 9 },
        { id: 'shortSword_t4', weight: 9 },
        { id: 'axe_t1', weight: 7 },
        { id: 'axe_t2', weight: 7 },
        { id: 'axe_t3', weight: 7 },
        { id: 'axe_t4', weight: 7 },
        { id: 'twoHandedSword_t1', weight: 5 },
        { id: 'twoHandedSword_t2', weight: 5 },
        { id: 'twoHandedSword_t3', weight: 5 },
        { id: 'twoHandedSword_t4', weight: 5 },
        { id: 'bow_t1', weight: 3 },
        { id: 'bow_t2', weight: 3 },
        { id: 'bow_t3', weight: 3 },
        { id: 'bow_t4', weight: 3 },
        { id: 'crossbow_t1', weight: 2 },
        { id: 'crossbow_t2', weight: 2 },
        { id: 'crossbow_t3', weight: 2 },
        { id: 'crossbow_t4', weight: 2 },
        { id: 'armor_t1', weight: 1 },
        { id: 'armor_t2', weight: 1 },
        { id: 'armor_t3', weight: 1 },
        { id: 'armor_t4', weight: 1 },
    ],
};

export const encounterBalance = {
    encounterRate: 0.1,
    discoveredEncounterRate: 0.05,
    minEnemies: 1,
    maxEnemies: 3,
    enemyWeights: { skeleton: 4, zombie: 2, ninja: 1, darkKnight: 1, dragon: 1 },
    eventTypeWeights: [{ type: 'monster', weight: 40 }, { type: 'item', weight: 10 }, { type: 'traveler', weight: 10 }],
    zombieMinGroup: 1,
    zombieMaxGroup: 2,
};
