import type { RandomEncounterType } from '../encounter/EncounterSystem.js';
import type { CombatMove } from '../combat/DirectionalCombat.js';

export type HudElements = {
    hudMenuToggleBtn: HTMLButtonElement;
    hudMenuPanel: HTMLElement;
    modeIndicator: HTMLElement;
    usePotionBtn: HTMLButtonElement;
    useManaPotionBtn: HTMLButtonElement;
    newCharacterBtn: HTMLButtonElement;
    worldMapZoomInBtn: HTMLButtonElement;
    worldMapZoomOutBtn: HTMLButtonElement;
    worldMapPanUpBtn: HTMLButtonElement;
    worldMapPanDownBtn: HTMLButtonElement;
    worldMapPanLeftBtn: HTMLButtonElement;
    worldMapPanRightBtn: HTMLButtonElement;
    playerLevel: HTMLElement;
    playerName: HTMLElement;
    playerXp: HTMLElement;
    playerXpNext: HTMLElement;
    playerHp: HTMLElement;
    playerMaxHp: HTMLElement;
    playerMana: HTMLElement;
    playerMaxMana: HTMLElement;
    playerDmg: HTMLElement;
    playerDmgFormula: HTMLElement;
    playerArmor: HTMLElement;
    playerDodge: HTMLElement;
    playerDodgeFormula: HTMLElement;
    playerWeapon: HTMLElement;
    playerGold: HTMLElement;
    skillPoints: HTMLElement;
    magicPoints: HTMLElement;
    magicPanelPoints: HTMLElement;
    statVitality: HTMLElement;
    statToughness: HTMLElement;
    statStrength: HTMLElement;
    statAgility: HTMLElement;
    statConnection: HTMLElement;
    statIntelligence: HTMLElement;
    addVitalityBtn: HTMLButtonElement;
    subVitalityBtn: HTMLButtonElement;
    addToughnessBtn: HTMLButtonElement;
    subToughnessBtn: HTMLButtonElement;
    addStrengthBtn: HTMLButtonElement;
    subStrengthBtn: HTMLButtonElement;
    addAgilityBtn: HTMLButtonElement;
    subAgilityBtn: HTMLButtonElement;
    addConnectionBtn: HTMLButtonElement;
    subConnectionBtn: HTMLButtonElement;
    addIntelligenceBtn: HTMLButtonElement;
    subIntelligenceBtn: HTMLButtonElement;
    saveSkillsBtn: HTMLButtonElement;
    godSkillsBtn: HTMLButtonElement;
    upgradeFireballBtn: HTMLButtonElement;
    upgradeCurseBtn: HTMLButtonElement;
    upgradeSlowBtn: HTMLButtonElement;
    upgradeRageBtn: HTMLButtonElement;
    upgradeArcaneLanceBtn: HTMLButtonElement;
    spellLevelFireball: HTMLElement;
    spellLevelCurse: HTMLElement;
    spellLevelSlow: HTMLElement;
    spellLevelRage: HTMLElement;
    spellLevelArcaneLance: HTMLElement;
    spellDetailsFireball: HTMLElement;
    spellDetailsCurse: HTMLElement;
    spellDetailsSlow: HTMLElement;
    spellDetailsRage: HTMLElement;
    spellDetailsArcaneLance: HTMLElement;
    inventoryCount: HTMLElement;
    inventoryCapacity: HTMLElement;
    inventoryCapacityHint: HTMLElement;
    undoLastDropBtn: HTMLButtonElement;
    inventoryGrid: HTMLElement;
    weaponSlotMain: HTMLButtonElement;
    weaponSlotOff: HTMLButtonElement;
    armorSlot: HTMLButtonElement;
    statsPanel: HTMLElement;
    skillsPanel: HTMLElement;
    inventoryPanel: HTMLElement;
    magicPanel: HTMLElement;
    questsPanel: HTMLElement;
    selectedPanel: HTMLElement;
    lorePanel: HTMLElement;
    worldMapPanel: HTMLElement;
    logPanel: HTMLElement;
    questsTitle: HTMLElement;
    questsBody: HTMLElement;
    loreBody: HTMLElement;
    selectedCellEmpty: HTMLElement;
    selectedCellDetails: HTMLElement;
    selectedCellCoords: HTMLElement;
    selectedCellTerrain: HTMLElement;
    selectedCellVisibility: HTMLElement;
    selectedCellTraversable: HTMLElement;
    selectedCellVillage: HTMLElement;
    selectedCellVillageName: HTMLElement;
    selectedCellVillageStatus: HTMLElement;
    toggleStatsPanelBtn: HTMLButtonElement;
    toggleSkillsPanelBtn: HTMLButtonElement;
    toggleInventoryPanelBtn: HTMLButtonElement;
    toggleMagicPanelBtn: HTMLButtonElement;
    toggleQuestsPanelBtn: HTMLButtonElement;
    toggleLorePanelBtn: HTMLButtonElement;
    toggleSelectedPanelBtn: HTMLButtonElement;
    toggleWorldMapPanelBtn: HTMLButtonElement;
    toggleLogPanelBtn: HTMLButtonElement;
    questIntroModal: HTMLElement;
    questIntroBody: HTMLElement;
    questIntroCloseBtn: HTMLButtonElement;
};

export type BattleUI = {
    sidebar: HTMLElement;
    enemyName: HTMLElement;
    enemyHp: HTMLElement;
    enemyMaxHp: HTMLElement;
    attackBtn: HTMLButtonElement;
    directionalButtons: Record<CombatMove, HTMLButtonElement>;
    fleeBtn: HTMLButtonElement;
    waitBtn: HTMLButtonElement;
    usePotionBtn: HTMLButtonElement;
    useManaPotionBtn: HTMLButtonElement;
    spellFireballBtn: HTMLButtonElement;
    spellCurseBtn: HTMLButtonElement;
    spellSlowBtn: HTMLButtonElement;
    spellRageBtn: HTMLButtonElement;
    spellArcaneLanceBtn: HTMLButtonElement;
    attackRangeText: HTMLElement;
};

export type WorldUI = {
    sidebar: HTMLElement;
    usePotionBtn: HTMLButtonElement;
    enterVillageBtn: HTMLButtonElement;
    centerOnCharacterBtn: HTMLButtonElement;
};

export type VillageUI = {
    sidebar: HTMLElement;
    title: HTMLElement;
    prompt: HTMLElement;
    actions: HTMLElement;
    enterBtn: HTMLButtonElement;
    skipBtn: HTMLButtonElement;
    waitBtn: HTMLButtonElement;
    buyOffer1Btn: HTMLButtonElement;
    buyOffer2Btn: HTMLButtonElement;
    buyOffer3Btn: HTMLButtonElement;
    buyOffer4Btn: HTMLButtonElement;
    sellSelect: HTMLSelectElement;
    sellSelectedBtn: HTMLButtonElement;
    npcList: HTMLElement;
    npcTitle: HTMLElement;
    askVillageInput: HTMLInputElement;
    askVillageBtn: HTMLButtonElement;
    askPersonInput: HTMLInputElement;
    askPersonBtn: HTMLButtonElement;
    askBarterBtn: HTMLButtonElement;
    barterNowBtn: HTMLButtonElement;
    leaveBtn: HTMLButtonElement;
};

export type DeveloperUI = {
    modal: HTMLElement;
    closeBtn: HTMLButtonElement;
    eventType: HTMLSelectElement;
    queueList: HTMLElement;
    addBtn: HTMLButtonElement;
    clearBtn: HTMLButtonElement;
    encounterTypeSummary: HTMLElement;
    enableAllEncountersBtn: HTMLButtonElement;
    disableAllEncountersBtn: HTMLButtonElement;
    encounterTypeToggles: Record<RandomEncounterType, HTMLInputElement>;
    nextRollOpenBtn: HTMLButtonElement;
    nextRollSummary: HTMLElement;
    nextRollModal: HTMLElement;
    nextRollCloseBtn: HTMLButtonElement;
    nextRollTotal: HTMLElement;
    nextRollStatus: HTMLElement;
    nextRollSaveBtn: HTMLButtonElement;
    nextRollClearBtn: HTMLButtonElement;
    nextRollInputs: Record<'vitality' | 'toughness' | 'strength' | 'agility' | 'connection' | 'intelligence', HTMLInputElement>;
    randomModeSelect: HTMLSelectElement;
    randomSeedInput: HTMLInputElement;
    randomSummary: HTMLElement;
    randomStatus: HTMLElement;
    randomApplyBtn: HTMLButtonElement;
    everythingDiscoveredToggle: HTMLInputElement;
    fogOfWarToggle: HTMLInputElement;
};

export type GameLogUI = {
    log: HTMLElement;
};

export type GameUiBundle = {
    hudElements: HudElements;
    worldUI: WorldUI;
    battleUI: BattleUI;
    villageUI: VillageUI;
    gameLogUI: GameLogUI;
    developerUI: DeveloperUI;
};
