// Generated by Duud
// Exports only slider/keyframe data for the selected animation

import type { ImportedAnimationMeta, ImportedKeyframe } from '../types.js';

export const AXE_KICK2_KEYFRAMES: ImportedKeyframe[] = [
    {
        time: 0,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 30,
            shoulderLength: 30,
            leftShoulderAngle: -0.25,
            leftElbowAngle: 2.6,
            rightShoulderAngle: 1.05,
            rightElbowAngle: 2.1,
            leftHipAngle: -0.04,
            leftKneeAngle: -0.06,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.04
        }
    },
    {
        time: 1,
        params: {
            x: 400,
            y: 300,
            headTilt: -0.12,
            torsoAngle: -0.18,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 30,
            shoulderLength: 33,
            leftShoulderAngle: -1.2,
            leftElbowAngle: 0.8,
            rightShoulderAngle: 1.0,
            rightElbowAngle: 0.85,
            leftHipAngle: -1.2,
            leftKneeAngle: -1.2,
            rightHipAngle: -0.03,
            rightKneeAngle: -0.03
        }
    },
    {
        time: 2,
        params: {
            x: 401,
            y: 300,
            headTilt: -0.27,
            torsoAngle: -0.33,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 30,
            shoulderLength: 34,
            leftShoulderAngle: -1.45,
            leftElbowAngle: 0.45,
            rightShoulderAngle: 1.25,
            rightElbowAngle: 0.6,
            leftHipAngle: -1.57,
            leftKneeAngle: -0.2,
            rightHipAngle: -0.04,
            rightKneeAngle: -0.04
        }
    },
    {
        time: 3,
        params: {
            x: 402,
            y: 300,
            headTilt: 0.05,
            torsoAngle: 0.2,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 29,
            shoulderLength: 33,
            leftShoulderAngle: -0.35,
            leftElbowAngle: -0.2,
            rightShoulderAngle: 0.1,
            rightElbowAngle: 1.3,
            leftHipAngle: 1.25,
            leftKneeAngle: -0.06,
            rightHipAngle: -0.03,
            rightKneeAngle: -0.04
        }
    },
    {
        time: 4,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 30,
            shoulderLength: 30,
            leftShoulderAngle: -0.23,
            leftElbowAngle: 2.7,
            rightShoulderAngle: 1.08,
            rightElbowAngle: 2.15,
            leftHipAngle: -0.04,
            leftKneeAngle: -0.06,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.04
        }
    }
];

export const AXE_KICK2_META: ImportedAnimationMeta = {
    name: 'AxeKick2',
    duration: 4,
    loop: false
};
