// Generated by Duud
// Exports only slider/keyframe data for the selected animation

import type { ImportedAnimationMeta, ImportedKeyframe } from '../types.js';

export const AXE_KICK_KEYFRAMES: ImportedKeyframe[] = [
    {
        time: 0,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 30,
            shoulderLength: 30,
            leftShoulderAngle: -0.23,
            leftElbowAngle: 2.7,
            rightShoulderAngle: 1.08,
            rightElbowAngle: 2.15,
            leftHipAngle: -0.04,
            leftKneeAngle: -0.06,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.04
        }
    },
    {
        time: 1,
        params: {
            x: 381,
            y: 306,
            headTilt: -0.03,
            torsoAngle: 0.6,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 30,
            rightForearmLength: 27,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 27,
            shoulderLength: 35,
            leftShoulderAngle: -0.55,
            leftElbowAngle: 0.35,
            rightShoulderAngle: 1.81,
            rightElbowAngle: -2.09,
            leftHipAngle: -0.17,
            leftKneeAngle: 0.02,
            rightHipAngle: 2.76,
            rightKneeAngle: -0.04
        }
    },
    {
        time: 2,
        params: {
            x: 393,
            y: 301,
            headTilt: 0.14,
            torsoAngle: 0.26,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 30,
            rightForearmLength: 27,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 27,
            shoulderLength: 35,
            leftShoulderAngle: -0.33,
            leftElbowAngle: 1.44,
            rightShoulderAngle: 0.44,
            rightElbowAngle: -0.23,
            leftHipAngle: -0.17,
            leftKneeAngle: 0.020000000000000004,
            rightHipAngle: 0.26,
            rightKneeAngle: -0.04
        }
    },
    {
        time: 3,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 30,
            shoulderLength: 30,
            leftShoulderAngle: -0.23,
            leftElbowAngle: 2.7,
            rightShoulderAngle: 1.08,
            rightElbowAngle: 2.15,
            leftHipAngle: -0.04,
            leftKneeAngle: -0.06,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.04
        }
    }
];

export const AXE_KICK_META: ImportedAnimationMeta = {
    name: "AxeKick1",
    duration: 3,
    loop: false
};
