// Generated by Duud
// Exports only slider/keyframe data for the selected animation

import type { ImportedAnimationMeta, ImportedKeyframe } from '../types.js';

export const DEATH_KEYFRAMES: ImportedKeyframe[] = [
    {
        time: 0,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: 0.22,
            leftElbowAngle: 2.74,
            rightShoulderAngle: 1.05,
            rightElbowAngle: 2.1,
            leftHipAngle: -0.03,
            leftKneeAngle: -0.04,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.03
        }
    },
    {
        time: 0.5082089552238807,
        params: {
            x: 351,
            y: 306,
            headTilt: -0.39894402985074634,
            torsoAngle: 0.39894402985074634,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: -0.22976492537313434,
            leftElbowAngle: 2.0412126865671643,
            rightShoulderAngle: 1.1719701492537313,
            rightElbowAngle: 1.5917910447761194,
            leftHipAngle: 0.3765671641791045,
            leftKneeAngle: -0.04,
            rightHipAngle: 0.3687798507462687,
            rightKneeAngle: 0.03
        }
    },
    {
        time: 1.0119402985074626,
        params: {
            x: 328,
            y: 331,
            headTilt: -1.57,
            torsoAngle: 0.7943731343283582,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: -0.6755671641791045,
            leftElbowAngle: 1.3485820895522391,
            rightShoulderAngle: 1.292865671641791,
            rightElbowAngle: 1.0880597014925375,
            leftHipAngle: 0.7795522388059701,
            leftKneeAngle: -0.04,
            rightHipAngle: 0.7541343283582089,
            rightKneeAngle: 0.03
        }
    },
    {
        time: 2,
        params: {
            x: 284,
            y: 420,
            headTilt: -1.57,
            torsoAngle: 1.57,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: -1.55,
            leftElbowAngle: -0.01,
            rightShoulderAngle: 1.53,
            rightElbowAngle: 0.1,
            leftHipAngle: 1.57,
            leftKneeAngle: -0.04,
            rightHipAngle: 1.51,
            rightKneeAngle: 0.03
        }
    }
];

export const DEATH_META: ImportedAnimationMeta = {
    name: "Death",
    duration: 2,
    loop: false
};
