// Generated by Duud
// Exports only slider/keyframe data for the selected animation

import type { ImportedAnimationMeta, ImportedKeyframe } from '../types.js';

export const HURT_KEYFRAMES: ImportedKeyframe[] = [
    {
        time: 0,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: 0.22,
            leftElbowAngle: 2.74,
            rightShoulderAngle: 1.05,
            rightElbowAngle: 2.1,
            leftHipAngle: -0.03,
            leftKneeAngle: -0.04,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.03
        }
    },
    {
        time: 1,
        params: {
            x: 404,
            y: 313,
            headTilt: -1.05,
            torsoAngle: 0.42,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: -0.15,
            leftElbowAngle: 2.41,
            rightShoulderAngle: 1.23,
            rightElbowAngle: 1.7,
            leftHipAngle: -0.16,
            leftKneeAngle: -0.07,
            rightHipAngle: -0.06,
            rightKneeAngle: 0.03
        }
    },
    {
        time: 2,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: 0.22,
            leftElbowAngle: 2.74,
            rightShoulderAngle: 1.05,
            rightElbowAngle: 2.1,
            leftHipAngle: -0.03,
            leftKneeAngle: -0.04,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.03
        }
    }
];

export const HURT_META: ImportedAnimationMeta = {
    name: "Hurt",
    duration: 2,
    loop: false
};
