// Generated by Duud
// Exports only slider/keyframe data for the selected animation

import type { ImportedAnimationMeta, ImportedKeyframe } from '../types.js';

export const KICK2_KEYFRAMES: ImportedKeyframe[] = [
    {
        time: 0,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 30,
            shoulderLength: 30,
            leftShoulderAngle: -0.23,
            leftElbowAngle: 2.7,
            rightShoulderAngle: 1.08,
            rightElbowAngle: 2.15,
            leftHipAngle: -0.04,
            leftKneeAngle: -0.06,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.04
        }
    },
    {
        time: 1,
        params: {
            x: 400,
            y: 300,
            headTilt: -0.03,
            torsoAngle: 0.27,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 27,
            shoulderLength: 35,
            leftShoulderAngle: -0.55,
            leftElbowAngle: 0.35,
            rightShoulderAngle: 0.82,
            rightElbowAngle: -0.27,
            leftHipAngle: 0,
            leftKneeAngle: 0.02,
            rightHipAngle: -0.74,
            rightKneeAngle: -1.57
        }
    },
    {
        time: 2,
        params: {
            x: 400,
            y: 300,
            headTilt: -0.09,
            torsoAngle: 0.32,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 27,
            shoulderLength: 35,
            leftShoulderAngle: -0.55,
            leftElbowAngle: -0.03,
            rightShoulderAngle: 0.22,
            rightElbowAngle: -0.27,
            leftHipAngle: 0.05,
            leftKneeAngle: -0.05,
            rightHipAngle: 1.57,
            rightKneeAngle: -0.15
        }
    },
    {
        time: 3,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 30,
            shoulderLength: 30,
            leftShoulderAngle: -0.23,
            leftElbowAngle: 2.7,
            rightShoulderAngle: 1.08,
            rightElbowAngle: 2.15,
            leftHipAngle: -0.04,
            leftKneeAngle: -0.06,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.04
        }
    }
];

export const KICK2_META: ImportedAnimationMeta = {
    name: "Kick2",
    duration: 3,
    loop: false
};
