// Generated by Duud
// Exports only slider/keyframe data for the selected animation

import type { ImportedAnimationMeta, ImportedKeyframe } from '../types.js';

export const STRONG_PUNCH_KEYFRAMES: ImportedKeyframe[] = [
    {
        time: 0,
        params: {
            x: 384,
            y: 307,
            headTilt: -0.28,
            torsoAngle: 0.44,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: -0.88,
            leftElbowAngle: 3.14,
            rightShoulderAngle: 1.05,
            rightElbowAngle: 2.1,
            leftHipAngle: -0.03,
            leftKneeAngle: -0.04,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.03
        }
    },
    {
        time: 1,
        params: {
            x: 409,
            y: 302,
            headTilt: 0.57,
            torsoAngle: -0.18,
            torsoLength: 50,
            leftUpperArmLength: 46,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 28,
            shoulderLength: 25,
            leftShoulderAngle: 1.48,
            leftElbowAngle: 0.1,
            rightShoulderAngle: 0.31,
            rightElbowAngle: 1.27,
            leftHipAngle: -0.03,
            leftKneeAngle: -0.04,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.03
        }
    },
    {
        time: 2,
        params: {
            x: 400,
            y: 300,
            headTilt: 0,
            torsoAngle: 0,
            torsoLength: 50,
            leftUpperArmLength: 35,
            leftForearmLength: 30,
            rightUpperArmLength: 35,
            rightForearmLength: 30,
            leftThighLength: 40,
            leftCalfLength: 35,
            rightThighLength: 40,
            rightCalfLength: 35,
            hipLength: 19,
            shoulderLength: 26,
            leftShoulderAngle: 0.22,
            leftElbowAngle: 2.74,
            rightShoulderAngle: 1.05,
            rightElbowAngle: 2.1,
            leftHipAngle: -0.03,
            leftKneeAngle: -0.04,
            rightHipAngle: -0.02,
            rightKneeAngle: 0.03
        }
    }
];

export const STRONG_PUNCH_META: ImportedAnimationMeta = {
    name: "StrongPunch",
    duration: 2,
    loop: false
};
